trigger: none

pool:
  name: 'agent-pool-1'


steps:
- checkout: self
  displayName: 'Checkout repository'

- task: TerraformInstaller@1
  displayName: 'Install Terraform'
  inputs:
    terraformVersion: 'latest'
    
- task: TerraformTaskV4@4
  displayName: Terraform init
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'Azure for Students(3f0f1366-aba7-4984-a589-fbc0bfc1159c)'
    backendAzureRmResourceGroupName: 'myrg-1.0'
    backendAzureRmStorageAccountName: 'mysac17xf9mz2mqjf0f9'
    backendAzureRmContainerName: 'myfirstcontainer'
    backendAzureRmKey: 'tf/terraform.tfstate'

- task: TerraformTaskV4@4
  displayName: 'Terraform Validate'
  inputs:
    command: 'validate'
    workingDirectory: '$(System.DefaultWorkingDirectory)'

- task: TerraformTaskV4@4
  displayName: 'Terraform Plan'
  inputs:
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
    commandOptions: '-out=tfplan'
    environmentServiceNameAzureRM: 'Azure for Students(3f0f1366-aba7-4984-a589-fbc0bfc1159c)'

- task: TerraformTaskV4@4
  displayName: 'Terraform Apply'
  inputs:
    command: 'apply'
    commandOptions: '-auto-approve -input=false tfplan'



