# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: agent-pool-1

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
- task: NodeTool@0
  inputs:
    versionSource: 'spec'
    versionSpec: '6.x'
    checkLatest: true
    nodejsMirror: 'npm'
  displayName: 'Run a multi-line script'
