trigger: none
stages:
  - stage: 'Install'
    displayName: 'Intalling the Terraform'
    jobs:
      - job: 'Installation'
        displayName: 'Installation'
        pool:
          name: 'agent-pool-1'
        steps: 
        - task: TerraformInstaller@1
          inputs:
           terraformVersion: 'latest'

  - stage: 
    displayName: 'Initiating Terraform'
    jobs:
      - job: 'Initiate'
        displayName: 'Initiating terraform'
        pool: 
          name: 'agent-pool-1'
        steps:
        - task: TerraformTaskV4@4
          inputs:
            provider: 'azurerm'
            command: 'init'
            backendServiceArm: 'Azure for Students(3f0f1366-aba7-4984-a589-fbc0bfc1159c)'
            backendAzureRmResourceGroupName: 'myrg-1.0'
            backendAzureRmStorageAccountName: 'mysac17xf9mz2mqjf0f9'
            backendAzureRmContainerName: 'myfirstcontainer'
            backendAzureRmKey: 'tf/terraform.tfstate'
  - stage: 
    displayName: 'Validating Terraform'
    jobs:
        - job: 'Validate'
          displayName: 'Validating terraform'
          pool: 
            name: 'agent-pool-1'
          steps:
          - task: TerraformTaskV3@3
            displayName: 'Terraform Validate'
            inputs:
              provider: 'azurerm'
              command: 'validate'
              workingDirectory: '$(System.DefaultWorkingDirectory)'
              backendServiceArm: 'Azure for Students(3f0f1366-aba7-4984-a589-fbc0bfc1159c)'
              backendAzureRmResourceGroupName: 'myrg-1.0'
              backendAzureRmStorageAccountName: 'mysac17xf9mz2mqjf0f9'
              backendAzureRmContainerName: 'myfirstcontainer'
              backendAzureRmKey: 'tf/terraform.tfstate'
             
