# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: agent-pool-1

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'init'
    commandOptions: '-out tfvalidate -out tfplan -out tfapply'
    backendServiceArm: 'Azure for Students(3f0f1366-aba7-4984-a589-fbc0bfc1159c)'
    backendAzureRmResourceGroupName: 'myrg-1.0'
    backendAzureRmStorageAccountName: 'mysagj2bf1onzs9hncug'
    backendAzureRmContainerName: 'myfirstcontainer'
    backendAzureRmKey: 'tf/terraform.tfstate'
    
