# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- block


pool:
  name: agent-pool-1

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Hello Terraform Azure Pipeline'

- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'Azure for Students(3f0f1366-aba7-4984-a589-fbc0bfc1159c)'
    backendAzureRmResourceGroupName: 'myrg-1.0'
    backendAzureRmStorageAccountName: 'mysac17xf9mz2mqjf0f9'
    backendAzureRmContainerName: 'myfirstcontainer'
    backendAzureRmKey: 'tf/terraform.tfstate'
  
- script: |
    cd $(workingDirectory)
    terraform plan -out=tfplan
  displayName: 'Terraform Plan'

- script: |
    cd $(workingDirectory)
    terraform apply -auto-approve tfplan
  displayName: 'Terraform Apply'



